[package]
name = "boombots-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ws = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
boombots-core = { path = "../core" } 
